### PR TITLE
fix: search for go.mod up until home folder

### LINKED ISSUE #103: bug: error running tests from a lower working directory
### Did you check docs and existing issues?

- [X] I have read the [documentation](https://github.com/fredrikaverpil/neotest-golang/blob/main/README.md).
- [X] I have searched the existing [issues](https://github.com/fredrikaverpil/neotest-golang/issues).

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

The adapter is limiting its search for the `go.mod` file to the current working directory and this is causing test commands to fail.

### Steps To Reproduce

1. Create a go project with a valid `go.mod` file at its root, but with packages in subdirectories.
2. Change directory into one of the packages
3. Run the tests, for example `lua require("neotest").run.run( vim.fn.expand("%:h"))`. This produces a notification with the error
    >  Error  10:46:51 notify.error The selected folder must contain a go.mod file or be a subdirectory of a Go package.

### Expected Behavior

Tests for the package should run

### Your Lua setup

_No response_

### PR DESCRIPTION
**Pull request by fredrikaverpil**
Fix #103

```lua
  {
    "nvim-neotest/neotest",
    ft = { "go" },
    dependencies = {
      {
        "fredrikaverpil/neotest-golang",
        branch = "fix/expand-upwards-search",  -- ADD THIS
      },
    },
    opts = function(_, opts)
      opts.adapters = opts.adapters or {}
      opts.adapters["neotest-golang"] = {
        dap_go_enabled = true,
      }
    end,
  },
```

### CODE REVIEW

File: lua/neotest-golang/path.lua [hunk 1]
```diff
@@ -10,7 +10,7 @@ function M.find_file_upwards(filename, start_path)
   local scan = require("plenary.scandir")
   local cwd = vim.fn.getcwd()
```
Comment (jstensland) [inline lua/neotest-golang/path.lua:11]: `cwd` is now unused

**Review by jstensland — COMMENTED** [review]
this addressed https://github.com/fredrikaverpil/neotest-golang/issues/103
